#!/bin/bash

# JIRA Refinement App Deployment Script
# This script generates OpenShift deployment manifests and optionally applies them

set -e

# Default values
MODE="dry-run"
JIRA_BASE_URL="https://issues.redhat.com"
YAML_FILE="jira-app-deployment.yaml"
APP_NAME="jira-refinement-app"
IMAGE="quay.io/vedantm/jira-refinement-app:latest"
NAMESPACE="${NAMESPACE:-$(oc project -q 2>/dev/null || echo 'default')}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print usage
usage() {
    echo "Usage: $0 [--dry-run | --execute]"
    echo ""
    echo "Options:"
    echo "  --dry-run   Generate the YAML file only (default)"
    echo "  --execute   Generate the YAML file and apply it to OpenShift"
    echo ""
    echo "Environment variables:"
    echo "  NAMESPACE   OpenShift namespace to deploy to (default: current project)"
    exit 1
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            MODE="dry-run"
            shift
            ;;
        --execute)
            MODE="execute"
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            usage
            ;;
    esac
done

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║       JIRA Refinement App - OpenShift Deployment           ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Display mode
if [[ "$MODE" == "dry-run" ]]; then
    echo -e "${YELLOW}Mode: DRY-RUN (YAML will be generated but not applied)${NC}"
else
    echo -e "${GREEN}Mode: EXECUTE (YAML will be generated and applied)${NC}"
fi
echo ""

# Prompt for JIRA API Key
echo -e "${BLUE}JIRA Base URL:${NC} $JIRA_BASE_URL"
echo ""
read -sp "$(echo -e ${BLUE}Enter your JIRA API Key: ${NC})" JIRA_API_KEY
echo ""

if [[ -z "$JIRA_API_KEY" ]]; then
    echo -e "${RED}Error: JIRA API Key cannot be empty${NC}"
    exit 1
fi

echo ""
echo -e "${BLUE}Generating ${YAML_FILE}...${NC}"

# Generate the YAML file (using stringData for plain text - Kubernetes handles encoding)
cat > "$YAML_FILE" << EOF
# JIRA Refinement App - OpenShift Deployment Manifests
# Generated by run-jira-refinement-app.sh
# Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

---
# Secret containing JIRA credentials
apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-secret
  labels:
    app: ${APP_NAME}
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  JIRA_BASE_URL: "${JIRA_BASE_URL}"
  JIRA_API_TOKEN: "${JIRA_API_KEY}"

---
# Deployment for the JIRA Refinement App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/name: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_NAME}
          image: ${IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
              name: http
          env:
            - name: JIRA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ${APP_NAME}-secret
                  key: JIRA_BASE_URL
            - name: JIRA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${APP_NAME}-secret
                  key: JIRA_API_TOKEN
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL

---
# Service to expose the deployment internally
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/component: service
spec:
  selector:
    app: ${APP_NAME}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  type: ClusterIP

---
# Route to expose the app externally
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/component: route
spec:
  to:
    kind: Service
    name: ${APP_NAME}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
EOF

echo -e "${GREEN}✓ Generated ${YAML_FILE}${NC}"
echo ""

# Show summary
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}Summary:${NC}"
echo -e "  • Secret:     ${APP_NAME}-secret"
echo -e "  • Deployment: ${APP_NAME}"
echo -e "  • Service:    ${APP_NAME}"
echo -e "  • Route:      ${APP_NAME}"
echo -e "  • Image:      ${IMAGE}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# Execute if requested
if [[ "$MODE" == "execute" ]]; then
    echo -e "${BLUE}Applying manifests to OpenShift...${NC}"
    
    # Check if oc is available
    if ! command -v oc &> /dev/null; then
        echo -e "${RED}Error: 'oc' command not found. Please install OpenShift CLI.${NC}"
        exit 1
    fi
    
    # Check if logged in
    if ! oc whoami &> /dev/null; then
        echo -e "${RED}Error: Not logged into OpenShift. Please run 'oc login' first.${NC}"
        exit 1
    fi
    
    echo -e "${YELLOW}Deploying to namespace: ${NAMESPACE}${NC}"
    
    # Apply the manifests
    oc apply -f "$YAML_FILE" -n "$NAMESPACE"
    
    echo ""
    echo -e "${GREEN}✓ Deployment complete!${NC}"
    echo ""
    
    # Wait for route and display URL
    echo -e "${BLUE}Waiting for route to be ready...${NC}"
    sleep 3
    
    ROUTE_URL=$(oc get route ${APP_NAME} -n "$NAMESPACE" -o jsonpath='{.spec.host}' 2>/dev/null || echo "")
    
    if [[ -n "$ROUTE_URL" ]]; then
        echo ""
        echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
        echo -e "${GREEN}Application URL: https://${ROUTE_URL}${NC}"
        echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
    fi
else
    echo -e "${YELLOW}To apply the manifests, run:${NC}"
    echo -e "  oc apply -f ${YAML_FILE}"
    echo ""
    echo -e "${YELLOW}Or re-run this script with --execute:${NC}"
    echo -e "  $0 --execute"
fi

echo ""
echo -e "${GREEN}Done!${NC}"

